spring:
  config:
   activate:
      on-profile: dev
  mail:
    host: smtp.gmail.com
    port: 587
    username: onlineshivendra@gmail.com
    password: upmf kcoh llfr jcuv
    properties:
       mail:
         smtp:
           auth: true
           starttls:
             enable: true
eureka:
  client:
     service-url:
         defaultZone: http://localhost:8092
server:
  port: 8091
