eureka:
  client:
    service-url:
     defaultZone: http://localhost:8092/eureka/
     
spring:  
  config:
     activate:
        on-profile: dev
  datasource:
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://172.17.0.1:5431/school?currentSchema=vidayala
    hikari:
      maximum-pool-size: 15
      minimum-idle: 10
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 8000
      validation-timeout: 3000      
  jpa:
    show-sql: true
    hibernate:
       ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    properties:
      hibernate:
        default_schema: vidayala
  servlet:
    multipart:
       enabled: true
       max-file-size: 2MB
       max-request-size: 2MB   

server:
  port: 8093     
